sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: shCdXsXiz6aOMrOe2AQpkSGVEaLATPgJnr4BbiqD45AJa58zuxmFYcRDThE0YR/DJaDSCaYMocPBi6tP1FhSIukKxuY+WM0A1WBJCHlkL0AL5Ruh/ZcCUon2ajtClmEfCBFuumdyTeStu2xAgeaq8JmKm29rwELgy5ibX8//Lct2Uzs1Wqh3xgJLL5a7M99Z+nn9UniGqxSgA80lrQeM60dYiun99cuOSa4zEIVxXcbxEjt05I9aLq5LtP3rXbawSJuDTD24N+ze2UQEi0GvP9e1N5lnTpcHOWhorcIBaHXp1pG5Bx+paCFaNYLIeZsP9u1mBzlz97XWUFP/EbBLcdQw4K+LnnSfeDFggOcqiCnoJTftdJdn5NLbA+xk9RIRO5yUxt9dBMrFFacxe3MfaqApNooiOspP/nJsxpXKCPjyJf+njSHP50BqmshPJiIFBDKwDEPytWgZjE325o8GrAFT2IJWjWiw95O/+9iKqPbk79gdLpf8y0ERVKon9vASoJUf/Gyt6iOjvfFDSIU85SxCMOSpzEFl7LtK0kZopMHhjJ4g9ah06+xI0DewG7Qbde5VcK94dafXV4bZLn1TgQYmT1b0nSdR8HE/Nd13+NCBg8kmtrKsvabEZYou6lE2/z1+rgnB6u5s7UQp/9sZEK3LuwtXhkhVN/3E013nT6c=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Peveril-of-the-Peak_5959
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy